blank_issues_enabled: true
contact_links:
  - name: â“ Help with issues in older versions of the CLI
    url: https://github.community/c/software-development/47
    about: Find/file tickets with the community
  - name: â­ï¸ Feature Request
    url: https://github.com/orgs/community/discussions/categories/npm
    about: Add your request or discuss the project w/ the community
  - name: ğŸ“ƒ RFC
    url: https://github.com/npm/rfcs
    about: Create a more formal proposal/idea via our RFC
  - name: ğŸš¥ Registry Status
    url: https://status.npmjs.org
    about: Check the current status of the website/registry
  - name: ğŸ—‚ Documentation
    url: https://docs.npmjs.com
    about: Preview our new docs
  - name: ğŸ“« Support
    url: https://github.community/
    about: For general support questions please open a topic over at github.community
   - name: ğŸš‘ Support Policy
    url: https://github.com/npm/cli/wiki/Support-Policy
    about: Information about what version(s) of the CLI we support
