blank_issues_enabled: true
contact_links:
  - name: ğŸ Bug v7
    url: https://github.com/npm/cli/issues/new?title=[BUG]%20%3Ctitle%3E&template=bug-7.md
    about: File a bug/issue against v7.x
  - name: ğŸ Bug v6
    url: https://github.com/npm/cli/issues/new?title=[BUG]%20%3Ctitle%3E&template=bug-6.md
    about: File a bug/issue against v6.x
  - name: â­ï¸ Feature Request
    url: https://github.com/npm/rfcs
    about: Feel free to add your idea or create a formal RFC
  - name: ğŸ“ƒ RFC
    url: https://github.com/npm/rfcs
    about: Create a more formal proposal/idea via our RFC
  - name: ğŸš¥ Registry Status
    url: https://status.npmjs.org
    about: Check the current status of the website/registry
  - name: ğŸ—‚ Documentation
    url: https://preview-docs.npmjs.com/cli-commands/npm
    about: Preview our new docs
  - name: ğŸ“« Support
    url: https://npm.community
    about: Links to other support options &/or community references
